### ISSUE TITLE
How to handle token expired?

### ISSUE THREAD

**Issue by macist-m** [twitchtv/node-apicalypse#17]
Hello,

How would one handle a 401 returning from the api? 

I usually use axios interceptors or something in that nature to listen for a token expired call...

Thanks...

**Comment by krazyjakee** [comment]
Refresh the token and it should work.

**Comment by ChrisLFieldsII** [comment]
> Refresh the token and it should work.

This answer doesn't seem satisfactory for cases where using apicalyspe client to access an api that requires an access token which may be expired.

In that case as @macist-m mentioned, an Axios response interceptor is perfect to do the refresh logic @krazyjakee referred to. 

However I noticed that apicalypse doesnt currently give devs an easy to way to tap into the underlying axios instance to attach custom interceptors

I am looking to patch the package in the meanwhile to accomplish this with something like this that allows the `apicalypse.request` method to take an optional argument with an interceptors config that can be passed to underlying axios instance config (its rough and is not actually tested)

```javascript
  async request(url, {interceptors}) {
    // this is modified code
    const instance = await axios.create()
    instance.interceptors.request.use(interceptors.request)
    instance.interceptors.response.use(interceptors.response)
    const response = await instance(this.constructOptions(url))
    return response

    // this is original code
    // const response = await axios.create()(this.constructOptions(url));
    // return response;
  }
```
