### ISSUE TITLE
High severity vulnerability on npm install.

### ISSUE THREAD

**Issue by ndeamador** [twitchtv/node-apicalypse#18]
Hi there, I am getting a `found 1 high severity vulnerability` when installing the package with npm. Running `npm audit fix` does nothing.

![image](https://user-images.githubusercontent.com/50785597/112602366-acfd7700-8e67-11eb-8bbb-a29c41a2a1aa.png)

Is that something that could be solved? Is it ok to just ignore it?

**Comment by krazyjakee** [comment]
thank you, the vulnerability has been fixed in the latest version.
